"""End-to-end tests for the parse → validate → emit pipeline.

Runs against the fixtures generated by `python fixtures/build_fixture.py`.
"""
from __future__ import annotations
import subprocess
import sys
from pathlib import Path
import yaml

ROOT = Path(__file__).parent.parent
FIXTURES = ROOT / "fixtures"


def _ensure_fixtures():
    if not (FIXTURES / "single_file" / "hk-prod.excalidraw").exists():
        subprocess.check_call([sys.executable, str(FIXTURES / "build_fixture.py")])


def _run(*args):
    env = {"PYTHONPATH": str(ROOT / "src")}
    proc = subprocess.run(
        [sys.executable, "-m", "routingtools.cli", *args],
        cwd=str(ROOT), env={**__import__("os").environ, **env},
        capture_output=True, text=True,
    )
    return proc


def test_single_file_summary():
    _ensure_fixtures()
    proc = _run("summary", "fixtures/single_file/manifest.yaml")
    assert proc.returncode == 0, proc.stderr
    out = proc.stdout
    assert "Nodes: 4" in out
    assert "client: 1" in out
    assert "client_route: 1" in out
    assert "feed: 2" in out
    assert "Routes (edges): 3" in out


def test_multi_file_topology(tmp_path):
    _ensure_fixtures()
    proc = _run("build", "fixtures/multi_file/manifest.yaml", "--out", str(tmp_path))
    assert proc.returncode == 0, proc.stderr
    data = yaml.safe_load((tmp_path / "topology.yaml").read_text())
    nodes = data["nodes"]

    # All 7 expected nodes present.
    assert set(nodes) == {
        "hk-desk-7", "hk-route-1", "hk-hkex-trades",
        "hkny-bridge.hk", "hkny-bridge.ny",
        "ny-route-1", "ny-bloomberg-trades",
    }

    # Bridge halves are paired.
    assert nodes["hkny-bridge.hk"]["pair"] == "hkny-bridge.ny"
    assert nodes["hkny-bridge.ny"]["pair"] == "hkny-bridge.hk"

    # Feed is a sink.
    assert "routes" not in nodes["hk-hkex-trades"]
    assert "routes" not in nodes["ny-bloomberg-trades"]

    # Client has exactly one default hop.
    desk_routes = nodes["hk-desk-7"]["routes"]
    assert len(desk_routes) == 1
    assert desk_routes[0].get("default") is True
    assert desk_routes[0]["next_hop"] == "hk-route-1"

    # Route node has the expected keyed routes.
    route_routes = nodes["hk-route-1"]["routes"]
    matches = [tuple(r["match"]) for r in route_routes if "match" in r]
    assert ("bloomberg", "trade", "*", "*") in matches
    assert ("*", "*", "*", "hkex") in matches


def test_csv_emit(tmp_path):
    _ensure_fixtures()
    proc = _run("build", "fixtures/multi_file/manifest.yaml", "--out", str(tmp_path),
                "--format", "csv")
    assert proc.returncode == 0, proc.stderr
    csv_text = (tmp_path / "topology.csv").read_text()
    lines = csv_text.strip().splitlines()
    # Header + 6 edges
    assert len(lines) == 7
    assert lines[0].startswith("from,env_from,source")


def test_mermaid_emit(tmp_path):
    _ensure_fixtures()
    proc = _run("build", "fixtures/single_file/manifest.yaml", "--out", str(tmp_path),
                "--format", "mermaid")
    assert proc.returncode == 0, proc.stderr
    text = (tmp_path / "topology.mermaid").read_text()
    assert text.startswith("flowchart LR")
    # All four nodes present as Mermaid node definitions.
    assert "hk-desk-7" in text
    assert "hk-route-1" in text
    assert "hk-bbg-feed" in text
    assert "hk-default-feed" in text
    # Edges with expected labels.
    assert '"default"' in text
    assert '"bloomberg trade * *"' in text


def test_validation_fails_when_feed_has_outbound(tmp_path):
    """Construct a tiny diagram where a feed has an outbound and confirm validator fails."""
    import json
    fixture_dir = tmp_path / "broken"
    fixture_dir.mkdir()

    # Two ellipses connected by an arrow — both classify as feed,
    # so the source feed will have an outbound -> error.
    elements = []
    elements.append({
        "id": "f1", "type": "ellipse", "x": 0, "y": 0, "width": 100, "height": 60,
        "strokeColor": "#000", "backgroundColor": "#2dd4bf", "fillStyle": "solid",
        "strokeWidth": 1, "strokeStyle": "solid", "roughness": 0, "opacity": 100,
        "groupIds": [], "frameId": None, "roundness": None, "seed": 1,
        "version": 1, "versionNonce": 1, "isDeleted": False, "boundElements": [
            {"type": "text", "id": "t1"}], "updated": 1, "link": None, "locked": False, "angle": 0,
    })
    elements.append({
        "id": "t1", "type": "text", "x": 0, "y": 0, "width": 100, "height": 20,
        "text": "feed-a", "fontSize": 16, "fontFamily": 1,
        "textAlign": "center", "verticalAlign": "middle", "containerId": "f1",
        "strokeColor": "#000", "backgroundColor": "transparent", "fillStyle": "solid",
        "strokeWidth": 1, "strokeStyle": "solid", "roughness": 0, "opacity": 100,
        "groupIds": [], "frameId": None, "roundness": None, "seed": 2,
        "version": 1, "versionNonce": 2, "isDeleted": False, "boundElements": [],
        "updated": 1, "link": None, "locked": False, "angle": 0,
        "originalText": "feed-a", "lineHeight": 1.25, "baseline": 16, "autoResize": True,
    })
    elements.append({
        "id": "f2", "type": "ellipse", "x": 200, "y": 0, "width": 100, "height": 60,
        "strokeColor": "#000", "backgroundColor": "#2dd4bf", "fillStyle": "solid",
        "strokeWidth": 1, "strokeStyle": "solid", "roughness": 0, "opacity": 100,
        "groupIds": [], "frameId": None, "roundness": None, "seed": 3,
        "version": 1, "versionNonce": 3, "isDeleted": False, "boundElements": [
            {"type": "text", "id": "t2"}], "updated": 1, "link": None, "locked": False, "angle": 0,
    })
    elements.append({
        "id": "t2", "type": "text", "x": 200, "y": 0, "width": 100, "height": 20,
        "text": "feed-b", "fontSize": 16, "fontFamily": 1,
        "textAlign": "center", "verticalAlign": "middle", "containerId": "f2",
        "strokeColor": "#000", "backgroundColor": "transparent", "fillStyle": "solid",
        "strokeWidth": 1, "strokeStyle": "solid", "roughness": 0, "opacity": 100,
        "groupIds": [], "frameId": None, "roundness": None, "seed": 4,
        "version": 1, "versionNonce": 4, "isDeleted": False, "boundElements": [],
        "updated": 1, "link": None, "locked": False, "angle": 0,
        "originalText": "feed-b", "lineHeight": 1.25, "baseline": 16, "autoResize": True,
    })
    elements.append({
        "id": "a1", "type": "arrow", "x": 100, "y": 30, "width": 100, "height": 1,
        "strokeColor": "#000", "backgroundColor": "transparent", "fillStyle": "solid",
        "strokeWidth": 1, "strokeStyle": "solid", "roughness": 0, "opacity": 100,
        "groupIds": [], "frameId": None, "roundness": None, "seed": 5,
        "version": 1, "versionNonce": 5, "isDeleted": False, "boundElements": [],
        "updated": 1, "link": None, "locked": False, "angle": 0,
        "points": [[0, 0], [100, 0]],
        "startBinding": {"elementId": "f1", "focus": 0, "gap": 4},
        "endBinding": {"elementId": "f2", "focus": 0, "gap": 4},
        "startArrowhead": None, "endArrowhead": "arrow", "elbowed": False,
        "lastCommittedPoint": None,
    })

    (fixture_dir / "bad.excalidraw").write_text(json.dumps({
        "type": "excalidraw", "version": 2, "source": "test",
        "elements": elements, "appState": {}, "files": {},
    }))
    (fixture_dir / "manifest.yaml").write_text(
        "version: 1\n"
        "files:\n"
        "  - path: bad.excalidraw\n"
        "    scope: { region: hk, environment: prod }\n"
        "enums:\n"
        "  sources: [bloomberg]\n"
        "  types: [trade]\n"
        "  exchanges: [nyse]\n"
        "  environments: [prod]\n"
        "  regions: [hk]\n"
    )
    proc = _run("validate", str(fixture_dir / "manifest.yaml"))
    assert proc.returncode != 0
    assert "FEED_HAS_OUTBOUND" in proc.stderr
